"use client";

import { useEffect, useMemo, useState } from "react";

type Task = { id: string; date: string; description: string; assignedTo: string; remark?: string };
const KEY = "worklog.tasks.v2";
const ASSIGNED_KEY = "worklog.assignedTo.v1";
const today = new Date().toISOString().slice(0, 10);
function formatDate(date: string) { return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(`${date}T00:00:00`)); }
function shortDate(date: string) { return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${date}T00:00:00`)); }
function dayName(date: string) { return new Intl.DateTimeFormat("en-IN", { weekday: "long" }).format(new Date(`${date}T00:00:00`)); }
function getWeekStart(date: string) { const d = new Date(`${date}T00:00:00`); const day = d.getDay(); d.setDate(d.getDate() - (day === 0 ? 6 : day - 1)); return d.toISOString().slice(0, 10); }
function getWeekDates(date: string) { const start = new Date(`${getWeekStart(date)}T00:00:00`); return Array.from({ length: 6 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return d.toISOString().slice(0, 10); }); }

function buildChatGPTPrompt(type: "daily" | "weekly", entries: Task[], rangeLabel: string) {
  const grouped = entries.reduce<Record<string, Task[]>>((acc, task) => { (acc[task.date] ??= []).push(task); return acc; }, {});
  const taskText = Object.entries(grouped).map(([date, tasks]) => `### ${dayName(date)} | ${formatDate(date)}\n${tasks.map(t => `- ${t.description} (Assigned To: ${t.assignedTo})`).join("\n")}`).join("\n\n");
  if (type === "daily") {
    return `I am preparing my daily work report for my manager.\n\nDate: ${formatDate(entries[0]?.date ?? today)}\n\nTASKS:\n${taskText}\n\nPlease write ONE professional manager-facing "Remark" for this day. Summarize the actual work, campaign/content focus, workload, and meaningful implementation details only when supported by the tasks. Do not invent facts, numbers, achievements, blockers, or outcomes. Keep it to 2-3 polished sentences. Return only the remark, without a heading.`;
  }
  return `I am preparing my weekly work report for my manager.\n\nPeriod: ${rangeLabel}\n\nWORK LOG:\n${taskText}\n\nPlease create a professional weekly report summary. Mention the major areas of work, notable campaigns/projects, workload patterns, and technical/design implementation details only when supported by the logged tasks. Do not invent facts, numbers, achievements, blockers, or outcomes. Keep it concise but useful for a manager. Return only the "Weekly Summary" paragraph(s), without a heading.`;
}

async function openChatGPTWithPrompt(prompt: string) {
  try { await navigator.clipboard.writeText(prompt); } catch { /* Clipboard permissions can vary by browser. */ }
  window.open("https://chatgpt.com/?q=" + encodeURIComponent(prompt), "_blank", "noopener,noreferrer");
}

export default function Home() {
  const [tasks, setTasks] = useState<Task[]>([]); const [date, setDate] = useState(today); const [description, setDescription] = useState(""); const [assignedTo, setAssignedTo] = useState("Designer"); const [reportTitle, setReportTitle] = useState("Weekly Design Task Tracker"); const [notice, setNotice] = useState(""); const [summary, setSummary] = useState("");
  useEffect(() => { try { const saved = localStorage.getItem(KEY); const savedAssigned = localStorage.getItem(ASSIGNED_KEY); if (saved) setTasks(JSON.parse(saved)); if (savedAssigned) setAssignedTo(savedAssigned); } catch { setNotice("Could not read saved tasks."); } }, []);
  useEffect(() => localStorage.setItem(KEY, JSON.stringify(tasks)), [tasks]); useEffect(() => localStorage.setItem(ASSIGNED_KEY, assignedTo), [assignedTo]);
  const weekDates = useMemo(() => getWeekDates(date), [date]); const weekTasks = useMemo(() => tasks.filter(t => weekDates.includes(t.date)), [tasks, weekDates]); const monthTasks = useMemo(() => tasks.filter(t => t.date.startsWith(date.slice(0, 7))), [tasks, date]); const groupedWeek = useMemo(() => weekDates.map(d => ({ date: d, tasks: weekTasks.filter(t => t.date === d) })), [weekDates, weekTasks]); const rangeLabel = `${shortDate(weekDates[0])} – ${shortDate(weekDates[weekDates.length - 1])}`;
  function addTask() { if (!description.trim()) { setNotice("Add a task description first."); return; } setTasks(current => [...current, { id: crypto.randomUUID(), date, description: description.trim(), assignedTo: assignedTo.trim() || "Designer" }]); setDescription(""); setNotice("Task saved."); }
  function removeTask(id: string) { setTasks(current => current.filter(task => task.id !== id)); }
  function exportCsv(scope: "week" | "month") { const data = scope === "week" ? weekTasks : monthTasks; const rows = [["#", "Day", "Date", "Task Description", "Assigned To"], ...data.map((task, index) => [index + 1, dayName(task.date), formatDate(task.date), task.description, task.assignedTo])]; const csv = rows.map(row => row.map(v => `"${String(v).replaceAll('"', '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); a.download = `design-task-tracker-${scope}-${date}.csv`; a.click(); }
  function printReport(scope: "week" | "month") { const groups = scope === "week" ? groupedWeek : Array.from(new Set(monthTasks.map(t => t.date))).sort().map(d => ({ date: d, tasks: monthTasks.filter(t => t.date === d) })); const heading = scope === "week" ? `Weekly Design Task Tracker | ${rangeLabel}` : `Monthly Design Task Tracker`; const rows = groups.flatMap(group => group.tasks.map((task, i) => `<tr><td>${i === 0 ? group.tasks.indexOf(task) + 1 : ""}</td><td>${i === 0 ? `<strong>${dayName(group.date)}</strong>` : ""}</td><td>${i === 0 ? `<em>${formatDate(group.date)}</em>` : ""}</td><td>${task.description}</td><td>${task.assignedTo}</td></tr>`)).join(""); const win = window.open("", "_blank"); if (!win) return; win.document.write(`<html><head><title>${heading}</title><style>body{font-family:Arial;padding:32px;color:#111}h1{text-align:center;font-size:20px;margin:0 0 24px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:9px;text-align:left;vertical-align:top;font-size:12px}th{text-align:center;background:#f3f3f3}</style></head><body><h1>🎨 ${heading}</h1><table><thead><tr><th>#</th><th>Day</th><th>Date</th><th>Task Description</th><th>Assigned To</th></tr></thead><tbody>${rows}</tbody></table></body></html>`); win.document.close(); win.focus(); win.print(); }
  function generateDailyRemark() { const data = tasks.filter(task => task.date === date); if (!data.length) { setNotice("Add at least one task first."); return; } const prompt = buildChatGPTPrompt("daily", data, rangeLabel); setNotice("Opening ChatGPT with today's task context. The prompt is also copied to your clipboard."); void openChatGPTWithPrompt(prompt); }
  function generateWeeklySummary() { if (!weekTasks.length) { setNotice("Add at least one task first."); return; } const prompt = buildChatGPTPrompt("weekly", weekTasks, rangeLabel); setNotice("Opening ChatGPT with the weekly report context. The prompt is also copied to your clipboard."); void openChatGPTWithPrompt(prompt); }
  async function downloadWord() { if (!weekTasks.length) { setNotice("Add at least one task first."); return; } setNotice("Generating Word report…"); const res = await fetch("/api/report/word", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entries: weekTasks, summary }) }); if (!res.ok) { setNotice("Could not generate Word report."); return; } const blob = await res.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `weekly-work-report-${date}.docx`; a.click(); URL.revokeObjectURL(url); setNotice("Word report downloaded."); }
  return <main className="shell">
    <header className="topbar"><div><div className="eyebrow">WORKLOG / REPORTING</div><h1>Daily work, organized like your manager&apos;s tracker.</h1><p>Log multiple tasks against a date, then send the complete context to ChatGPT for manager-ready remarks and summaries.</p></div><div className="top-actions"><button className="ghost" onClick={() => printReport("week")}>Print report</button><button className="primary" onClick={downloadWord}>Download Word</button></div></header>
    <section className="editor card"><div className="card-head"><div><span className="kicker">NEW TASK</span><h2>Add work to a specific day</h2></div><input className="date" type="date" value={date} onChange={e => setDate(e.target.value)} /></div><div className="editor-grid"><label>Task description<input value={description} onChange={e => setDescription(e.target.value)} placeholder="e.g. Create 2 Blog Banner" onKeyDown={e => { if (e.key === "Enter") addTask(); }} /></label><label>Assigned to<input value={assignedTo} onChange={e => setAssignedTo(e.target.value)} placeholder="Designer" /></label><button className="primary add" onClick={addTask}>+ Add task</button></div>{notice && <div className="notice">{notice}</div>}</section>
    <section className="report card"><div className="report-toolbar"><div><span className="kicker">REPORT PREVIEW</span><h2>🎨 {reportTitle} <span>| {rangeLabel}</span></h2></div><div className="report-actions"><input className="title-input" value={reportTitle} onChange={e => setReportTitle(e.target.value)} aria-label="Report title" /><button className="ghost" onClick={generateDailyRemark}>✦ Generate Daily Remark in ChatGPT</button></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Day</th><th>Date</th><th>Task Description</th><th>Assigned To</th><th className="action-col"></th></tr></thead><tbody>{groupedWeek.flatMap(group => group.tasks.map((task, taskIndex) => <tr key={task.id}><td>{taskIndex === 0 ? weekTasks.findIndex(t => t.id === task.id) + 1 : ""}</td><td>{taskIndex === 0 ? <strong>{dayName(group.date)}</strong> : ""}</td><td>{taskIndex === 0 ? <em>{formatDate(group.date)}</em> : ""}</td><td>{task.description}{task.remark && <div className="ai-remark">Remark: {task.remark}</div>}</td><td>{task.assignedTo}</td><td className="action-col"><button onClick={() => removeTask(task.id)}>×</button></td></tr>))}{!weekTasks.length && <tr><td colSpan={6} className="empty-row">No tasks for this week. Add your first task above.</td></tr>}</tbody></table></div></section>
    <section className="bottom-grid"><div className="card summary-card"><div><span className="kicker">CHATGPT WEEKLY SUMMARY</span><h2>Manager-ready summary</h2><p>{summary || "Send the selected week to ChatGPT and ask it to write your professional weekly summary."}</p></div><button className="primary" onClick={generateWeeklySummary}>✦ Generate in ChatGPT</button></div><div className="card export-card"><span className="kicker">EXPORT</span><h2>Ready to mail</h2><p>Generate the remark or summary in ChatGPT, then paste the result into the report before downloading Word.</p><div className="export-buttons"><button className="ghost" onClick={() => exportCsv("week")}>Weekly CSV</button><button className="ghost" onClick={() => exportCsv("month")}>Monthly CSV</button><button className="ghost" onClick={() => printReport("month")}>Monthly PDF</button><button className="primary" onClick={downloadWord}>Word .docx</button></div></div></section>
    <footer>Worklog · table-first reporting · no OpenAI API key required</footer>
  </main>;
}
