"use client";

import { useEffect, useMemo, useState } from "react";

type Task = { id: string; date: string; description: string; assignedTo: string; driveLink?: string; remark?: string };
const KEY = "worklog.tasks.v2";
const ASSIGNED_KEY = "worklog.assignedTo.v1";
const REPORT_KEY = "worklog.overallReport.v1";
function dateKey(d: Date) { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
const today = dateKey(new Date());
function parseDate(date: string) { const [y, m, d] = date.split("-").map(Number); return new Date(y, m - 1, d); }
function formatDate(date: string) { return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "long", year: "numeric" }).format(parseDate(date)); }
function shortDate(date: string) { return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(parseDate(date)); }
function dayName(date: string) { return new Intl.DateTimeFormat("en-IN", { weekday: "long" }).format(parseDate(date)); }
function getWeekStart(date: string) { const d = parseDate(date); const day = d.getDay(); d.setDate(d.getDate() - (day === 0 ? 6 : day - 1)); return dateKey(d); }
function getWeekDates(date: string) { const start = parseDate(getWeekStart(date)); return Array.from({ length: 6 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return dateKey(d); }); }
function buildOverallReportPrompt(entries: Task[], rangeLabel: string) { const grouped = entries.reduce<Record<string, Task[]>>((acc, task) => { (acc[task.date] ??= []).push(task); return acc; }, {}); const taskText = Object.entries(grouped).map(([date, tasks]) => `### ${dayName(date)} | ${formatDate(date)}\n${tasks.map(t => `- ${t.description} (Assigned To: ${t.assignedTo})`).join("\n")}${tasks[0]?.driveLink ? `\n- Work Files: ${tasks[0].driveLink}` : ""}`).join("\n\n"); return `I am preparing my weekly work report for my manager.\n\nPeriod: ${rangeLabel}\n\nWORK LOG:\n${taskText}\n\nCreate the COMPLETE weekly work report in exactly this structure:\n\n# 🎨 Weekly Work Report\n\nPeriod: ${rangeLabel}\n\n### Monday | 17 August 2026\n\n- Created **1 LinkedIn Post** for Money Expo.\n- Designed **1 PR Banner**.\n\n**Work Files:** https://drive.google.com/example\n\n**Remark:**\n\nWrite a professional 2-3 sentence remark based only on that day's logged work.\n\n---\n\nRepeat the same structure for every day that has tasks. Use the real day and date from the work log. If a Drive link is provided for a day, include it once under that day's tasks as **Work Files:** followed by the exact link. If no link is provided, do not invent one. After all days, add:\n\n## Weekly Summary\n\nWrite a polished manager-facing weekly summary covering the major areas of work, notable campaigns/projects, workload patterns, and technical/design implementation details only when supported by the logged tasks.\n\nIMPORTANT RULES:\n- Keep the exact report structure shown above.\n- Use the actual first-task date as the beginning of the Period and the actual last-task date as the end of the Period.\n- Use a bullet for every logged task.\n- Keep each day's tasks grouped under that day.\n- Generate a separate **Remark:** for every day.\n- Generate one **Weekly Summary** at the end.\n- Preserve every provided Drive link exactly.\n- Do not invent facts, numbers, achievements, blockers, technical work, or outcomes.\n- Return ONLY the complete report.`; }
async function openChatGPTWithPrompt(prompt: string) { try { await navigator.clipboard.writeText(prompt); } catch {} window.open("https://chatgpt.com/?q=" + encodeURIComponent(prompt), "_blank", "noopener,noreferrer"); }
function cleanEmailBody(report: string, entries: Task[]) { let lines = report.trim().split(/\r?\n/); while (lines.length && !lines[0].trim()) lines.shift(); while (lines.length && !lines[lines.length - 1].trim()) lines.pop(); if (lines.length && /^#?\s*🎨?\s*WEEKLY WORK REPORT\s*$/i.test(lines[0].trim())) lines.shift(); while (lines.length && !lines[0].trim()) lines.shift(); if (lines.length && /^Period\s*:\s*.+$/i.test(lines[0].trim())) lines.shift(); while (lines.length && !lines[0].trim()) lines.shift(); const grouped = entries.reduce<Record<string, Task[]>>((acc, task) => { (acc[task.date] ??= []).push(task); return acc; }, {}); const output: string[] = []; for (const line of lines) { output.push(line); const match = line.match(/^###\s+.+\|\s*(\d{1,2}\s+\w+\s+\d{4})\s*$/); if (match) { const date = Object.keys(grouped).find(d => formatDate(d) === match[1]); const link = date ? grouped[date][0]?.driveLink : undefined; if (link && !lines.some(existing => existing.includes(link))) output.push(`**Work Files:** ${link}`); } } return output.join("\n").trim(); }

const taskEditStyles = `
.task-actions{display:flex;align-items:center;gap:4px;flex:0 0 auto}
.task-actions button{border:0;background:transparent;color:#a0a5af;cursor:pointer;padding:5px 6px;border-radius:7px;font-size:17px;line-height:1}
.task-actions button:hover{background:#f5f3ff;color:#7355f5}
.task-edit-card{display:block}
.task-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}
.task-edit-grid label{display:flex;flex-direction:column;gap:5px;color:#7f8592;font-size:9px;font-weight:750}
.task-edit-grid input{width:100%;height:38px;border:1px solid #dedfe6;background:#fafbfc;color:#242731;border-radius:9px;outline:none;padding:9px 10px;font:inherit;font-size:11px}
.task-edit-grid input:focus{border-color:#9a86f4;background:#fff;box-shadow:0 0 0 3px #7657f514}
.task-edit-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:10px}
.tracker-scroll-fix{max-height:555px;overflow-y:auto;overflow-x:hidden;padding-right:5px;scrollbar-width:thin;scrollbar-color:#cfc9f8 transparent}
.tracker-scroll-fix::-webkit-scrollbar{width:6px}
.tracker-scroll-fix::-webkit-scrollbar-track{background:transparent}
.tracker-scroll-fix::-webkit-scrollbar-thumb{background:#d2ccf7;border-radius:10px}
.delete-modal-backdrop{position:fixed;inset:0;background:rgba(20,22,30,.42);backdrop-filter:blur(3px);display:flex;align-items:center;justify-content:center;padding:20px;z-index:1000}
.delete-modal{width:min(420px,100%);background:#fff;border:1px solid #ececf1;border-radius:18px;box-shadow:0 24px 70px rgba(20,22,30,.2);padding:24px;color:#242731}
.delete-modal-icon{width:42px;height:42px;border-radius:12px;background:#fff1f1;color:#e14b4b;display:flex;align-items:center;justify-content:center;font-size:21px;margin-bottom:15px}
.delete-modal h3{margin:0 0 7px;font-size:18px;letter-spacing:-.02em}
.delete-modal p{margin:0;color:#7f8592;font-size:12px;line-height:1.55}
.delete-modal-task{margin-top:13px;padding:11px 12px;background:#f8f8fa;border:1px solid #ededf1;border-radius:10px;font-size:11px;font-weight:700;color:#3b3e48;line-height:1.45}
.delete-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}
.delete-modal .cancel-delete{border:1px solid #dedfe6;background:#fff;color:#5d6270;border-radius:9px;padding:9px 14px;font-size:11px;font-weight:750;cursor:pointer}
.delete-modal .confirm-delete{border:0;background:#e14b4b;color:#fff;border-radius:9px;padding:9px 15px;font-size:11px;font-weight:750;cursor:pointer;box-shadow:0 5px 12px rgba(225,75,75,.18)}
.delete-modal .confirm-delete:hover{background:#cf3e3e}
.delete-modal .cancel-delete:hover{background:#f7f7f9}
@media(max-width:900px){.tracker-scroll-fix{max-height:525px}}
@media(max-width:560px){.task-edit-grid{grid-template-columns:1fr}.task-edit-actions{display:grid;grid-template-columns:1fr 1fr}.task-edit-actions button{width:100%}.tracker-scroll-fix{max-height:465px}.delete-modal{padding:20px}.delete-modal-actions{display:grid;grid-template-columns:1fr 1fr}.delete-modal-actions button{width:100%}}
`;

export default function Home() {
  const [tasks,setTasks]=useState<Task[]>([]); const [date,setDate]=useState(today); const [description,setDescription]=useState(""); const [assignedTo,setAssignedTo]=useState("Designer"); const [driveLink,setDriveLink]=useState(""); const [notice,setNotice]=useState(""); const [overallReport,setOverallReport]=useState(""); const [sidebarCollapsed,setSidebarCollapsed]=useState(false); const [activeNav,setActiveNav]=useState("dashboard"); const [editingId,setEditingId]=useState<string|null>(null); const [editForm,setEditForm]=useState<Task|null>(null); const [deleteTask,setDeleteTask]=useState<Task|null>(null);
  useEffect(()=>{try{const saved=localStorage.getItem(KEY);const savedAssigned=localStorage.getItem(ASSIGNED_KEY);const savedReport=localStorage.getItem(REPORT_KEY);if(saved)setTasks(JSON.parse(saved));if(savedAssigned)setAssignedTo(savedAssigned);if(savedReport)setOverallReport(savedReport)}catch{setNotice("Could not read saved tasks.")}},[]);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify(tasks)),[tasks]); useEffect(()=>localStorage.setItem(ASSIGNED_KEY,assignedTo),[assignedTo]); useEffect(()=>localStorage.setItem(REPORT_KEY,overallReport),[overallReport]);
  const weekDates=useMemo(()=>getWeekDates(date),[date]); const weekTasks=useMemo(()=>tasks.filter(t=>weekDates.includes(t.date)),[tasks,weekDates]); const monthTasks=useMemo(()=>tasks.filter(t=>t.date.startsWith(date.slice(0,7))),[tasks,date]); const groupedWeek=useMemo(()=>weekDates.map(d=>({date:d,tasks:weekTasks.filter(t=>t.date===d)})).filter(g=>g.tasks.length),[weekDates,weekTasks]); const reportStartDate=weekTasks.length?[...weekTasks].sort((a,b)=>a.date.localeCompare(b.date))[0].date:date; const reportEndDate=weekTasks.length?[...weekTasks].sort((a,b)=>b.date.localeCompare(a.date))[0].date:date; const rangeLabel=`${shortDate(reportStartDate)} – ${shortDate(reportEndDate)}`; const activeDays=groupedWeek.length; const totalTasks=weekTasks.length;
  function goTo(id:string){setActiveNav(id);document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
  function addTask(){if(!description.trim()){setNotice("Add a task description first.");return}const existingDayLink=tasks.find(t=>t.date===date)?.driveLink;const dayDriveLink=existingDayLink||driveLink.trim()||undefined;setTasks(current=>[...current,{id:crypto.randomUUID(),date,description:description.trim(),assignedTo:assignedTo.trim()||"Designer",driveLink:dayDriveLink}]);setDescription("");setDriveLink(dayDriveLink||"");setNotice("Task saved successfully.")}
  function removeTask(id:string){setTasks(current=>current.filter(t=>t.id!==id));if(editingId===id){setEditingId(null);setEditForm(null)}setDeleteTask(null);setNotice("Task deleted successfully.")}
  function startEditTask(task:Task){setEditingId(task.id);setEditForm({...task});setNotice("")}
  function cancelEditTask(){setEditingId(null);setEditForm(null)}
  function saveEditTask(){if(!editForm||!editForm.description.trim()){setNotice("Add a task description first.");return}const oldDate=tasks.find(t=>t.id===editForm.id)?.date;const nextDate=editForm.date;const nextLink=editForm.driveLink?.trim()||undefined;setTasks(current=>current.map(t=>t.id===editForm.id?{...t,...editForm,description:editForm.description.trim(),assignedTo:editForm.assignedTo.trim()||"Designer",driveLink:nextLink}:t));if(nextLink)setTasks(current=>current.map(t=>t.date===nextDate?{...t,driveLink:nextLink}:t));else if(oldDate===nextDate)setTasks(current=>current.map(t=>t.date===nextDate?{...t,driveLink:undefined}:t));setEditingId(null);setEditForm(null);setNotice("Task updated successfully.")}
  function generateOverallReport(){if(!weekTasks.length){setNotice("Add at least one task first.");return}const prompt=buildOverallReportPrompt(weekTasks,rangeLabel);setNotice(`Opening ChatGPT with ${rangeLabel}. The complete prompt is also copied.`);void openChatGPTWithPrompt(prompt)}
  function exportCsv(scope:"week"|"month"){const data=scope==="week"?weekTasks:monthTasks;const rows=[["#","Day","Date","Task Description","Assigned To","Work Drive Link"],...data.map((t,i)=>[i+1,dayName(t.date),formatDate(t.date),t.description,t.assignedTo,t.driveLink||""])];const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`design-task-tracker-${scope}-${date}.csv`;a.click()}
  function printReport(scope:"week"|"month"){const groups=scope==="week"?groupedWeek:Array.from(new Set(monthTasks.map(t=>t.date))).sort().map(d=>({date:d,tasks:monthTasks.filter(t=>t.date===d)}));const heading=scope==="week"?`Weekly Design Task Tracker | ${rangeLabel}`:"Monthly Design Task Tracker";const rows=groups.flatMap(g=>g.tasks.map((t,i)=>`<tr><td>${i===0?g.tasks.indexOf(t)+1:""}</td><td>${i===0?`<strong>${dayName(g.date)}</strong>`:""}</td><td>${i===0?`<em>${formatDate(g.date)}</em>`:""}</td><td>${t.description}</td><td>${t.assignedTo}</td><td>${t.driveLink?`<a href="${t.driveLink}" target="_blank">${t.driveLink}</a>`:""}</td></tr>`)).join("");const win=window.open("","_blank");if(!win)return;win.document.write(`<html><head><title>${heading}</title><style>body{font-family:Arial;padding:32px;color:#111}h1{text-align:center;font-size:20px;margin:0 0 24px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:9px;text-align:left;vertical-align:top;font-size:12px}th{text-align:center;background:#f3f3f3}</style></head><body><h1>🎨 ${heading}</h1><table><thead><tr><th>#</th><th>Day</th><th>Date</th><th>Task Description</th><th>Assigned To</th><th>Work Drive Link</th></tr></thead><tbody>${rows}</tbody></table></body></html>`);win.document.close();win.focus();win.print()}
  async function downloadWord(){if(!weekTasks.length){setNotice("Add at least one task first.");return}if(!overallReport.trim()){setNotice("Paste the complete ChatGPT report above first.");return}setNotice("Formatting your report and creating the Word document…");const res=await fetch("/api/report/word",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entries:weekTasks,overallReport})});if(!res.ok){setNotice("Could not format the report. Please try again.");return}const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`weekly-work-report-${reportStartDate}-to-${reportEndDate}.docx`;a.click();URL.revokeObjectURL(url);setNotice("Formatted Word report downloaded.")}
  function emailReport(){if(!weekTasks.length){setNotice("Add at least one task first.");return}if(!overallReport.trim()){setNotice("Paste the complete ChatGPT report above first.");return}const subject=`Weekly Work Report | ${rangeLabel}`;const body=cleanEmailBody(overallReport,weekTasks);window.open(`https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,"_blank","noopener,noreferrer");setNotice("Opening Gmail with the subject and report body filled in.")}
  return <><style>{taskEditStyles}</style><div className={`app-shell ${sidebarCollapsed?"sidebar-collapsed":""}`}>
    <aside className="sidebar"><div className="sidebar-top"><div className="brand"><div className="brand-mark">W</div><div className="brand-copy"><strong>Worklog</strong><span>Design reporting</span></div></div><button className="sidebar-toggle" style={{position:"absolute",top:26,right:-14,width:28,height:28,borderRadius:"50%",zIndex:20,boxShadow:"0 4px 14px rgba(23,25,35,.12)",background:"#fff"}} onClick={()=>setSidebarCollapsed(v=>!v)}>{sidebarCollapsed?"›":"‹"}</button></div><nav><button className={`nav-item ${activeNav==="dashboard"?"active":""}`} onClick={()=>goTo("dashboard")}><span>▦</span><b>Dashboard</b></button><button className={`nav-item ${activeNav==="daily"?"active":""}`} onClick={()=>goTo("daily")}><span>✓</span><b>Daily Tasks</b></button><button className={`nav-item ${activeNav==="weekly"?"active":""}`} onClick={()=>goTo("weekly")}><span>▤</span><b>Weekly Report</b></button><button className={`nav-item ${activeNav==="monthly"?"active":""}`} onClick={()=>goTo("monthly")}><span>▥</span><b>Monthly Report</b></button></nav></aside>
    <main className="dashboard">
      <header id="dashboard" className="dashboard-header"><div><div className="eyebrow">WORKSPACE / REPORTING</div><h1>Good morning Rizwan Khan 👋</h1><p>Track your daily design work and turn it into a manager-ready report.</p></div><div className="header-actions"><button className="soft-btn" onClick={()=>printReport("week")}>↗ Print report</button><button className="dark-btn" onClick={downloadWord}>↓ Format & Download Word</button></div></header>
      <section className="stats-grid"><div className="stat-card"><div className="stat-icon purple">✓</div><div><span>Total tasks</span><strong>{totalTasks}</strong></div></div><div className="stat-card"><div className="stat-icon blue">◷</div><div><span>Active days</span><strong>{activeDays}</strong></div></div><div className="stat-card"><div className="stat-icon pink">▤</div><div><span>Report period</span><strong>{rangeLabel}</strong></div></div><div className="stat-card progress-stat"><div><span>Weekly progress</span><strong>{totalTasks?"On track":"Start logging"}</strong></div><div className="progress"><i style={{width:`${Math.min(100,activeDays/6*100)}%`}}/></div></div></section>
      <section id="daily" className="workspace-grid"><div className="panel add-panel"><div className="panel-title"><div><span className="kicker">DAILY TASKS</span><h2>Add work</h2></div><span className="date-pill">{shortDate(date)}</span></div><div className="form-stack"><label>Task description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="e.g. Create 2 Blog Banners" onKeyDown={e=>{if(e.key==="Enter")addTask()}}/></label><label>Date<input type="date" value={date} onChange={e=>{const next=e.target.value;setDate(next);setDriveLink(tasks.find(t=>t.date===next)?.driveLink||"")}}/></label><label>Assigned to<input value={assignedTo} onChange={e=>setAssignedTo(e.target.value)} placeholder="Designer"/></label><label>Today's work Drive link<input type="url" value={driveLink} onChange={e=>setDriveLink(e.target.value)} placeholder="https://drive.google.com/..." onKeyDown={e=>{if(e.key==="Enter")addTask()}}/></label><button className="dark-btn full" onClick={addTask}>+ Add task</button></div>{notice&&<div className="notice">{notice}</div>}</div>
      <div id="weekly" className="panel tracker-panel"><div className="panel-title"><div><span className="kicker">THIS PERIOD</span><h2>Weekly task tracker</h2></div><span className="period-pill">{rangeLabel}</span></div><div className="day-list tracker-scroll-fix">{groupedWeek.length?groupedWeek.map(group=><div className="day-group" key={group.date}><div className="day-head"><div><strong>{dayName(group.date)}</strong><span>{formatDate(group.date)}</span></div><b>{group.tasks.length} {group.tasks.length===1?"task":"tasks"}</b></div>{group.tasks.map(task=>editingId===task.id&&editForm?<div className="task-card task-edit-card" key={task.id}><div className="task-main"><div className="task-edit-grid"><label>Task description<input value={editForm.description} onChange={e=>setEditForm({...editForm,description:e.target.value})}/></label><label>Date<input type="date" value={editForm.date} onChange={e=>setEditForm({...editForm,date:e.target.value,driveLink:tasks.find(t=>t.date===e.target.value)?.driveLink||editForm.driveLink})}/></label><label>Assigned to<input value={editForm.assignedTo} onChange={e=>setEditForm({...editForm,assignedTo:e.target.value})}/></label><label>Work Drive link<input type="url" value={editForm.driveLink||""} onChange={e=>setEditForm({...editForm,driveLink:e.target.value})} placeholder="https://drive.google.com/..."/></label></div><div className="task-edit-actions"><button className="soft-btn" onClick={cancelEditTask}>Cancel</button><button className="dark-btn" onClick={saveEditTask}>Save changes</button></div></div></div>:<div className="task-card" key={task.id}><div className="task-dot"/><div className="task-main"><strong>{task.description}</strong><span>Assigned to {task.assignedTo}{task.driveLink?<> · <a href={task.driveLink} target="_blank" rel="noreferrer">Work files ↗</a></>:null}</span></div><div className="task-actions"><button onClick={()=>startEditTask(task)} aria-label="Edit task">✎</button><button onClick={()=>setDeleteTask(task)} aria-label="Delete task" title="Delete task">×</button></div></div>)}</div>):<div className="empty-state"><div>✦</div><strong>No tasks yet</strong><span>Add your first task to start the report.</span></div>}</div></div>
      <div className="panel report-panel"><div className="panel-title"><div><span className="kicker">REPORT</span><h2>Generate report</h2></div><div className="report-badge">ChatGPT</div></div><div className="report-hero"><div className="report-symbol">✦</div><h3>Complete weekly report</h3><p>Generate daily bullets, daily remarks and the final weekly summary using your saved tasks.</p><div className="period-box"><span>REPORT PERIOD</span><strong>{rangeLabel}</strong></div><button className="purple-btn full" onClick={generateOverallReport}>✦ Generate in ChatGPT</button><small>The prompt is copied automatically.</small></div><div className="export-row"><button className="soft-btn" onClick={()=>exportCsv("week")}>Weekly CSV</button><button className="soft-btn" onClick={downloadWord}>Format & Download Word</button></div></div></section>
      <section className="panel report-editor"><div className="panel-title"><div><span className="kicker">FINAL REPORT</span><h2>Paste & prepare your report</h2><p>Paste ChatGPT's complete response here. Worklog will format it into your manager-ready Word document.</p></div><span className="saved-pill">Auto-saved</span></div><textarea value={overallReport} onChange={e=>setOverallReport(e.target.value)} placeholder="Paste the complete ChatGPT report here…" rows={14}/><div className="editor-footer"><span>{overallReport.length?`${overallReport.length.toLocaleString()} characters saved`:"Paste the ChatGPT output to continue"}</span><div><button className="soft-btn" onClick={()=>setOverallReport("")}>Clear</button><button className="dark-btn" onClick={downloadWord}>↓ Format & Download Word</button><button className="gmail-btn" onClick={emailReport}>✉ Email via Gmail</button></div></div></section>
      <section id="monthly" className="bottom-strip"><div><span className="kicker">MONTHLY EXPORT</span><strong>Need the full month?</strong><span>Export your saved monthly task history.</span></div><div className="strip-actions"><button className="soft-btn" onClick={()=>exportCsv("month")}>Monthly CSV</button><button className="soft-btn" onClick={()=>printReport("month")}>Monthly PDF</button></div></section><footer>Worklog · cloud synced · ChatGPT-assisted reporting</footer>
    </main>
  </div>{deleteTask&&<div className="delete-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDeleteTask(null)}}><div className="delete-modal" role="dialog" aria-modal="true" aria-labelledby="delete-task-title"><div className="delete-modal-icon">!</div><h3 id="delete-task-title">Delete this task?</h3><p>This action cannot be undone. Are you sure you want to permanently remove this task?</p><div className="delete-modal-task">{deleteTask.description}</div><div className="delete-modal-actions"><button className="cancel-delete" onClick={()=>setDeleteTask(null)}>No, keep it</button><button className="confirm-delete" onClick={()=>removeTask(deleteTask.id)}>Yes, delete</button></div></div></div>}</>;
}
