"use client";
import { useEffect, useState } from "react";

type Mark = { id: string; date: string; type: "Leave" | "Holiday"; remark: string };
const KEY = "worklog.leaveHoliday.v1";

export default function LeaveHolidayWidget(){
 const [open,setOpen]=useState(false); const [date,setDate]=useState(""); const [type,setType]=useState<"Leave"|"Holiday">("Leave"); const [remark,setRemark]=useState("");
 useEffect(()=>{const handler=(e:Event)=>{const d=(e as CustomEvent<{date?:string}>).detail;setDate(d?.date||new Date().toISOString().slice(0,10));setType("Leave");setRemark("");setOpen(true)};window.addEventListener("worklog:open-leave-modal",handler);return()=>window.removeEventListener("worklog:open-leave-modal",handler)},[]);
 const save=()=>{if(!date)return;const items:Mark[]=JSON.parse(localStorage.getItem(KEY)||"[]");localStorage.setItem(KEY,JSON.stringify([...items.filter(x=>x.date!==date),{id:crypto.randomUUID(),date,type,remark:remark.trim()}]));window.dispatchEvent(new Event("worklog:leave-holiday-updated"));setOpen(false)};
 return <><div style={{marginTop:8}}><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent("worklog:open-leave-modal",{detail:{date:new Date().toISOString().slice(0,10)}}))} style={{border:"1px solid #dedfe6",background:"#fff",color:"#5d6270",borderRadius:9,padding:"9px 14px",fontWeight:750,cursor:"pointer",fontSize:11}}>Mark Leave / Holiday</button></div>{open&&<div style={{position:"fixed",inset:0,zIndex:2000,background:"rgba(20,22,30,.42)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}} onMouseDown={()=>setOpen(false)}><div style={{width:"min(420px,100%)",background:"#fff",borderRadius:18,padding:24,boxShadow:"0 24px 70px rgba(20,22,30,.2)"}} onMouseDown={e=>e.stopPropagation()}><h3 style={{margin:"0 0 16px"}}>Mark Leave / Holiday</h3><label>Date</label><input type="date" value={date} onChange={e=>setDate(e.target.value)} style={{width:"100%",height:40,boxSizing:"border-box",margin:"6px 0 14px",border:"1px solid #dedfe6",borderRadius:9,padding:"0 10px"}}/><div style={{display:"flex",gap:8,marginBottom:16}}>{(["Leave","Holiday"] as const).map(x=><button key={x} onClick={()=>setType(x)} style={{flex:1,height:38,border:"1px solid #dedfe6",borderRadius:9,background:type===x?"#7355f5":"#fff",color:type===x?"#fff":"#555",cursor:"pointer",fontWeight:700}}>{x}</button>)}</div><label>Remark</label><textarea value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Add a remark (optional)" spellCheck autoCorrect="on" style={{width:"100%",minHeight:90,boxSizing:"border-box",marginTop:6,border:"1px solid #dedfe6",borderRadius:9,padding:10}}/><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button onClick={()=>setOpen(false)} style={{border:"1px solid #dedfe6",background:"#fff",borderRadius:9,padding:"9px 15px",fontWeight:700,cursor:"pointer"}}>Cancel</button><button onClick={save} style={{border:0,background:"#7355f5",color:"#fff",borderRadius:9,padding:"9px 16px",fontWeight:700,cursor:"pointer"}}>Save</button></div></div></div>}</>}
